name: ğŸš€ Reusable Deploy Template

on:
  workflow_call:
    inputs:
      service_project_path:
        required: true
        type: string
      context:
        required: true
        type: string
      dotnet_version:
        required: false
        type: string
        default: "8.0.x"
    secrets:     
      SSH_PORT:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'PROD' || 'DEV' }}
    env:
      service_name: "${{vars.SERVICE_PREFIX}}.${{ inputs.context }}"      
      systemd_service_name:  "${{vars.SERVICE_PREFIX}}.${{ inputs.context }}.service"
      deploy_target: "${{vars.OUTER_PATH}}/${{vars.APP_PATH}}/${{ inputs.context }}"
    steps:

      - name: ğŸ§¾ Log workflow inputs
        run: |
          echo "=== INPUTS RECEIVED ==="
          echo "Service Name: $service_name"
          echo "Service Project Path: ${{ inputs.service_project_path }}"
          echo "Systemd Service Name: $systemd_service_name"
          echo "Deploy Target: $deploy_target"
          echo "Dotnet Version: ${{ inputs.dotnet_version }}"
          echo "========================"

    
      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: ğŸ—‚ï¸ Verify project path
        run: |
          echo "Project path: ${{ inputs.service_project_path }}"
          ls -la ${{ inputs.service_project_path }} || exit 1

      - name: ğŸ§± Restore dependencies
        run: dotnet restore ${{ inputs.service_project_path }}

      - name: ğŸ—ï¸ Build
        run: dotnet build ${{ inputs.service_project_path }} --configuration Release --no-restore

      - name: ğŸš€ Publish
        run: dotnet publish ${{ inputs.service_project_path }} --configuration Release --output ./publish/${{ inputs.service_project_path }}

      - name: ğŸ“¤ Upload to server (A2 Hosting)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./publish/${{ inputs.service_project_path }}/*
          target: ${{env.deploy_target}}

      - name: ğŸ” Restart systemd service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Restarting service: ${{env.systemd_service_name}}"
            sudo systemctl daemon-reload
            sudo systemctl restart  ${{env.systemd_service_name}}
            sudo systemctl status  ${{env.systemd_service_name}} --no-pager
