name: ðŸš€ Deploy Expense Service

on:
  push:
    branches:
      - dev/*

jobs:
  use-deploy-template:
    uses: ./.github/workflows/deploy-template.yml
    with:
      service_name: ${{vars.SERVICE_PREFIX}}.Expense
      systemd_service_name: ${{vars.SERVICE_PREFIX}}.Expense.service
      deploy_target: ${{vars.OUTER_PATH}}/${{vars.APP_PATH}}
      service_project_path: Kuaminika.KobFlow.API.Expense
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
